/*
 * opencog/gnc-cognitive/cognitive_engine.hpp
 *
 * GnuCash Cognitive Engine - AI-powered financial intelligence
 * Integrates OpenCog framework with GnuCash accounting
 *
 * Copyright (C) 2024 GnuCash Developers
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef GNC_COGNITIVE_ENGINE_HPP
#define GNC_COGNITIVE_ENGINE_HPP

#include <string>
#include <vector>
#include <memory>
#include <chrono>
#include <functional>

#include "../atomspace/atomspace.hpp"
#include "../pattern/pattern_match.hpp"
#include "../cogutil/counter.hpp"

namespace gnc {
namespace opencog {

/**
 * Financial insight type.
 */
enum class InsightType
{
    SPENDING_PATTERN,
    INCOME_PATTERN,
    ANOMALY,
    PREDICTION,
    CATEGORIZATION,
    BUDGET_ALERT,
    TREND,
    RECOMMENDATION
};

/**
 * Financial insight generated by the cognitive engine.
 */
struct FinancialInsight
{
    InsightType type;
    std::string title;
    std::string description;
    double confidence;
    std::chrono::system_clock::time_point timestamp;
    std::vector<std::string> related_accounts;
    std::vector<std::string> related_transactions;
};

/**
 * Transaction categorization result.
 */
struct CategorizationResult
{
    std::string category;
    double confidence;
    std::string reasoning;
    std::vector<std::string> alternative_categories;
};

/**
 * Spending pattern detected.
 */
struct SpendingPattern
{
    std::string name;
    std::string description;
    std::vector<std::string> accounts;
    double average_amount;
    std::string frequency;  // daily, weekly, monthly, etc.
    double confidence;
};

/**
 * CognitiveEngine - the main interface to GnuCash AI capabilities.
 *
 * This engine provides:
 * - Automatic transaction categorization
 * - Spending pattern recognition
 * - Anomaly detection
 * - Financial predictions
 * - Budget recommendations
 * - Natural language queries about finances
 */
class CognitiveEngine
{
public:
    using InsightCallback = std::function<void(const FinancialInsight&)>;

    CognitiveEngine();
    ~CognitiveEngine();

    /**
     * Initialize the cognitive engine.
     * Must be called before other operations.
     */
    bool initialize();

    /**
     * Shutdown the cognitive engine.
     */
    void shutdown();

    /**
     * Check if engine is initialized.
     */
    bool is_initialized() const { return m_initialized; }

    // =========================================
    // Knowledge Base Management
    // =========================================

    /**
     * Get the underlying AtomSpace.
     */
    AtomSpace& atomspace() { return m_atomspace; }
    const AtomSpace& atomspace() const { return m_atomspace; }

    /**
     * Import account structure into the knowledge base.
     */
    void import_account(const std::string& guid, const std::string& name,
                       const std::string& account_type, const std::string& parent_guid);

    /**
     * Import a transaction into the knowledge base.
     */
    void import_transaction(const std::string& guid, const std::string& description,
                           const std::string& date, double amount,
                           const std::string& debit_account, const std::string& credit_account);

    /**
     * Import a vendor/payee.
     */
    void import_vendor(const std::string& name, const std::string& category = "");

    // =========================================
    // Transaction Categorization
    // =========================================

    /**
     * Suggest a category for a transaction.
     */
    CategorizationResult categorize_transaction(const std::string& description,
                                                double amount,
                                                const std::string& vendor = "");

    /**
     * Learn from a user's categorization choice.
     */
    void learn_categorization(const std::string& description, const std::string& vendor,
                             const std::string& chosen_category);

    // =========================================
    // Pattern Recognition
    // =========================================

    /**
     * Detect spending patterns in the data.
     */
    std::vector<SpendingPattern> detect_spending_patterns();

    /**
     * Find recurring transactions.
     */
    std::vector<Handle> find_recurring_transactions();

    /**
     * Detect anomalous transactions.
     */
    std::vector<Handle> detect_anomalies(double threshold = 2.0);

    // =========================================
    // Predictions
    // =========================================

    /**
     * Predict future cash flow.
     */
    double predict_cash_flow(int days_ahead);

    /**
     * Predict upcoming expenses.
     */
    std::vector<std::pair<std::string, double>> predict_expenses(int days_ahead);

    // =========================================
    // Insights and Recommendations
    // =========================================

    /**
     * Generate financial insights.
     */
    std::vector<FinancialInsight> generate_insights();

    /**
     * Subscribe to insight notifications.
     */
    void subscribe_insights(InsightCallback callback);

    /**
     * Get budget recommendations.
     */
    std::vector<std::string> get_budget_recommendations();

    // =========================================
    // Natural Language Interface
    // =========================================

    /**
     * Query finances using natural language.
     */
    std::string query(const std::string& question);

    // =========================================
    // Statistics
    // =========================================

    /**
     * Get cognitive engine statistics.
     */
    struct Stats
    {
        size_t total_atoms;
        size_t accounts_known;
        size_t transactions_known;
        size_t patterns_detected;
        size_t categorization_rules;
    };

    Stats get_stats() const;

private:
    bool m_initialized;
    AtomSpace m_atomspace;

    // Categorization learning
    Counter<std::string> m_category_counts;
    std::unordered_map<std::string, Counter<std::string>> m_vendor_categories;
    std::unordered_map<std::string, Counter<std::string>> m_keyword_categories;

    // Pattern detection state
    std::vector<SpendingPattern> m_detected_patterns;

    // Insight subscribers
    std::vector<InsightCallback> m_insight_callbacks;

    // Internal helpers
    void build_initial_knowledge();
    void extract_keywords(const std::string& text, std::vector<std::string>& keywords);
    double calculate_pattern_strength(const HandleSeq& transactions);
    void notify_insight(const FinancialInsight& insight);
};

/**
 * Global cognitive engine instance.
 */
CognitiveEngine& cognitive_engine();

} // namespace opencog
} // namespace gnc

#endif // GNC_COGNITIVE_ENGINE_HPP
